spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.practicum.kafka.GenericAvroSerializer

app:
  kafka:
    topic: stats.user-actions.v1

grpc:
  server:
    port: 0
