spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm
    username: ewm
    password: ewm

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
        default_schema: public

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
